services:
  nifi:
    ports:
      - "8443:8443"
    image: apache/nifi:latest
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: nifi
      SINGLE_USER_CREDENTIALS_PASSWORD: nifinifinifi
      NIFI_JVM_HEAP_MAX: 2g